### ISSUE TITLE
currently having this issue 

### ISSUE THREAD

**Issue by atebitsy** [bcylin/QuickTableViewController#43]
-Swift.h:263:39: error: cannot find interface declaration for 'QuickTableViewController', superclass of
      'IPSettingsViewController'; did you mean 'UITableViewController'?
@interface IPSettingsViewController : QuickTableViewController
                                      ^~~~~~~~~~~~~~~~~~~~~~~~
                                      UITableViewController
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITableViewController.h:20:49: note: 'UITableViewController'
      declared here

**Comment by bcylin** [comment]
Unfortunately, it won't work because QuickTableViewController is not Objective-C compatible.

**Comment by MindfulOutlet** [comment]
oh it's worked in the past on version 1.1.1 but thank you for replying i appreciate it
